[[hooks]]

# Syncthing folder path
folder = "/data1"

# Event type, one of:
# file_down_sync_done: triggers when a file has been fully synchronized locally (see filter to match for a specific file)
# folder_down_sync_done: triggers when a folder has been fully synchronized locally
# file_conflict: triggers when Syncthing creates a conflict file due to a local synchronization conflict
# remote_file_conflict: triggers when Syncthing creates a conflict file due to a remote synchronization conflict
event = "file_down_sync_done"

# glob rule for specific file matching for file_down_sync_done events
#filter = "shopping-list.txt"

# command to run when event triggers
command = "echo 'stfef event triggered!'"

# Whether to allow several commands for the same hook to run simultaneously
# if false, and a burst of events comes, the commands will be skipped while the previous one is still running
# optional, defaults to false
allow_concurrent = false